### ISSUE TITLE
How to use azure Storage Account with k8s StatefulSet

### ISSUE THREAD

**Issue by rvashishth** [andyzhangx/demo#8]
If we use the default storage classes, it creates a storage account in the shadow resource group(MC_*), this resource group get deleted when we recreate the AKS cluster. 

What should be the steps to use an existing Storage Account with StatefulSet resource where ersistent Volume needs to be created dynamically using StatefulSet's `volumeClaimTemplate`.  I have already created a storageAccount in the same RG as the AKS.

I tried to use [secretkey and secretnamespae in storageClass, as mentioned in Kubernetes docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file) it ends up with error - `invalid option "secretName" for volume plugin kubernetes.io/azure-file`. 

When I don't define the secret key in storageAccout resource,  AKS tries to look for storage account in shadow resource group(MC_)

PoC spec file
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-standard-customtwo
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: True
parameters:
  skuName: Standard_LRS
  storageAccount: rahulpulsarpoc
  secretName: azuresecretname
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx2 # has to match .spec.template.metadata.labels
  serviceName: "nginx2"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: nginx2 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "azurefile-standard-customtwo"
        resources:
          requests:
            storage: 1Gi
```
